
SET(ZLIB_CMAKE_FLAGS
-DCMAKE_INSTALL_PREFIX=${CMAKE_EXTERNALS_DIR}zlib 
-DZLIB_ENABLE_TESTS=OFF 
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
)


ExternalProject_Add(zlib
PREFIX zlib
GIT_REPOSITORY    https://github.com/zlib-ng/zlib-ng
GIT_TAG           c882034d48afc0b32a38e8f7ca63a2e4e91ab42d
CMAKE_ARGS        ${ZLIB_CMAKE_FLAGS}
TEST_COMMAND      ""
)

IF (MSVC)
set(ZLIB_LIB_NAME ${CMAKE_STATIC_LIBRARY_PREFIX}zlibstatic-ng)
set(ZLIB_DPFIX d)
ELSE()
set(ZLIB_LIB_NAME ${CMAKE_STATIC_LIBRARY_PREFIX}z-ng${CMAKE_STATIC_LIBRARY_SUFFIX})
ENDIF()

add_library(zlib_lib STATIC IMPORTED)
set_target_properties(zlib_lib PROPERTIES IMPORTED_LOCATION ${CMAKE_EXTERNALS_DIR}zlib/${CMAKE_INSTALL_LIBDIR}/${ZLIB_LIB_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})
set_target_properties(zlib_lib PROPERTIES IMPORTED_LOCATION_DEBUG ${CMAKE_EXTERNALS_DIR}zlib/${CMAKE_INSTALL_LIBDIR}/${ZLIB_LIB_NAME}${ZLIB_DPFIX}${CMAKE_STATIC_LIBRARY_SUFFIX})

add_dependencies(zlib_lib zlib)

SET(ZLIB_LIBS "zlib_lib")
SET(ZLIB_INCLUDE_DIRS "${CMAKE_EXTERNALS_DIR}zlib/include/")